# Generated by Django 3.2.6 on 2021-08-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210813_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='message datetime'),
        ),
    ]
