# Generated by Django 3.2.6 on 2021-09-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_socket'),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='socket',
            field=models.IntegerField(default=0),
        ),
    ]
