# Generated by Django 3.2.6 on 2021-09-04 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_socket_socket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='message',
            name='socket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.socket'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
